import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Layout from "@/app/components/common/Layout";

import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Suspense
          // fallback={
          //   <div className="flex text-xl flex-col gap-2">Fallback2</div>
          // }
          >
            <main>{children}</main>
          </Suspense>
        </Layout>
      </body>
    </html>
  );
}
