export { default as Footer } from "./Footer";
//export { default as Layout } from "./Layout";
//export { default as Navbar } from "./Navbar";
//export { default as Navbar } from "./NavbarNew";
export { default as Searchbar } from "./Searchbar";
export { default as SEO } from "./SEO";
export { default as Clickoutside } from "./Clickoutside";
//export { default as Pagination } from "./Pagination";
//export { default as NavWrapper } from "./NavWrapper";
